services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception-network
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    networks:
      - inception-network
    volumes:
      -mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception-network
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
    
networks:
  inception-network:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o:  'bind'
      device: '~/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o:  'bind'
      device: '~/data/mariadb'